language: cpp
dist: bionic

notifications:
 email:
  recipients:
  - boutwork@gmail.com
  on_success: change
  on_failure: always

git:
 - strategy: clone
 - depth: 1
 
env:
 global:
  - MAKEFLAGS="-j 3"
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  
#cache:
# apt: true # misnommer: does not cache apt packages
# https://github.com/travis-ci/travis-ci/issues/5876#issuecomment-207661127

##### Phases
# https://docs.travis-ci.com/user/job-lifecycle#the-job-lifecycle

before_install:
 - eval "${MATRIX_EVAL}"

install:
 # Download and install recent cmake
 - |
   if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
     CMAKE_URL="http://www.cmake.org/files/v3.18/cmake-3.18.0-Linux-x86_64.tar.gz"
     mkdir -p ${DEPS_DIR}/cmake
     travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
     export PATH=${DEPS_DIR}/cmake/bin:${PATH}
   fi
 - cmake --version

script:
 - cmake -H. -Bbuild
 - cmake --build build
# -
# - cmake -H. -Bninja -GNinja
# - cmake --build ninja
 -
 - cmake -H. -Brelease -DCMAKE_BUILD_TYPE=Release
 - cmake --build release
 -
 - cmake -H. -Bdebug -DCMAKE_BUILD_TYPE=Debug
 - cmake --build debug

##### Stages

stages: # order
 - sanity
 - build
 - test

##### Jobs

os:
 - linux
# - windows # Add windows as build environnement, create additional jobs

#compiler: # can expand build matrix but without job naming and stage selection
# - gcc
# - clang
 
#env: #can expand build matrix
# - VAR_NAME=value

jobs: # alias matrix
 include:
  - name: "Trailing whitespace"
    stage: sanity
    script: |
     if [[ -n $(git diff --check HEAD^) ]]; then
       echo "You must remove whitespace before submitting a pull request"
       git diff --check HEAD^
       exit -1
     fi

  - name: "GCC 5"
    stage: build
    os: linux
    env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    addons:
     apt:
      sources: ubuntu-toolchain-r-test
      packages: g++-5

  - name: "GCC 6"
    stage: build
    os: linux
    env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    addons:
     apt:
      sources: ubuntu-toolchain-r-test
      packages: g++-6

  - name: "GCC 7"
    stage: build
    os: linux
    env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    addons:
     apt:
      sources: ubuntu-toolchain-r-test
      packages: g++-7

  - name: "Clang 4.0"
    stage: build
    os: linux
    env: MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    addons:
     apt:
      sources: llvm-toolchain-bionic-4.0
      packages: clang-4.0

  - name: "Clang 5.0"
    stage: build
    os: linux
    env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    addons:
     apt:
      sources: llvm-toolchain-bionic-5.0
      packages: clang-5.0
