language: cpp
dist: trusty
os: linux

notifications:
   email:
      recipients:
         - boutwork@gmail.com
      on_success: change
      on_failure: always

matrix:
   include:
      - os: linux
        env: NAME="Config"
        addons:
         apt:
          packages: ninja-build
        script:
         - cmake -H. -Brelease -DCMAKE_BUILD_TYPE=Release
         - cmake --build release -- -j 8
         - cmake --build release --target test
         - 
         - cmake -H. -Bdebug -DCMAKE_BUILD_TYPE=Debug
         - cmake --build debug -- -j 8
         - cmake --build debug --target test
         - 
         - cmake -H. -Bninja -GNinja
         - cmake --build ninja
         - cmake --build ninja --target test
      - os: linux
        env: NAME="Whitespace"
        script: |
         if [[ -n $(git diff --check HEAD^) ]]; then
           echo "You must remove whitespace before submitting a pull request"
           git diff --check HEAD^
           exit -1
         fi
      - os: linux
        env: NAME="CppCheck"
        script:
         - cmake -H. -Bbuild -DENABLE_CPPCHECK=ON
         - cmake --build build -- -j 8
         - cmake --build build --target check
      - os: linux
        env: NAME="Clang"
        addons:
         apt:
          source: llvm-toolchain-trusty-6.0
          packages: clang-6.0
        script:
         - cmake -H. -Brelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER="clang-6.0"
         - cmake --build release -- -j 8
         - cmake --build release --target test
         - 
         - cmake -H. -Bdebug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER="clang-6.0"
         - cmake --build debug -- -j 8
         - cmake --build debug --target test
